name: Feature Request / 功能请求
description: 建议新功能或改进 / Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 重要提示 / Important Notice

        ⚠️ **本项目仅支持离线使用场景，对于在线类软件（如网络游戏、在线服务、网盘等）的功能请求不提供支持。**
        
        ---
        
        感谢您的建议！请详细描述您希望添加的功能。
        

  - type: textarea
    id: problem
    attributes:
      label: 问题描述 / Problem Description
      description: 这个功能要解决什么问题？
      placeholder: 我在使用中遇到了...的问题
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案 / Proposed Solution
      description: 您希望如何实现这个功能？
      placeholder: 我建议添加一个...功能，可以...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案 / Alternatives Considered
      description: 您是否考虑过其他解决方案？
      placeholder: 我也考虑过...，但是...

  - type: textarea
    id: use-case
    attributes:
      label: 使用场景 / Use Case
      description: 这个功能在什么场景下会被使用？
      placeholder: 当我...的时候，我需要...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: 其他信息 / Additional Context
      description: 其他可能有助于理解该功能请求的信息
      placeholder: 相关链接、参考资料等

  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项 / Confirmation
      description: 请确认以下事项
      options:
        - label: 这个功能适用于离线软件场景 / This feature is for offline software scenarios
          required: true
        - label: 我已经搜索过现有的 issues，没有找到类似的功能请求 / I have searched existing issues and found no similar requests
          required: true
